In [1]:
%matplotlib inline
import warnings
warnings.filterwarnings(action='ignore')

# data
import pandas as pd
import numpy as np
import random as rnd


# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
pd.set_option('display.max_columns', 200)
pd.set_option('display.max_rows', 200)

In [3]:
longData = pd.read_csv('bdb copy.csv', low_memory = False)

In [4]:
longData.drop(longData[longData.DisplayName != "Kyle Long"].index, inplace=True)

In [5]:
longData.drop(columns=['DisplayName', 'JerseyNumber', 'NflId', 'PlayerHeight', 'PlayerWeight', 'PlayerBirthDate',
                      'PlayerCollegeName', 'Position', 'Location', 'WindSpeed', 'WindDirection', 'Team'], 
              axis=1, inplace=True)

In [6]:
# adjust GameClock to seconds left in quarter

def GameClockSeconds(GameClock):
    time_split = GameClock.split(':')
    seconds = int(time_split[0])*60 + int(time_split[1]) 
    return seconds

longData['GameClock'] = longData['GameClock'].apply(GameClockSeconds)

In [7]:
# fix offensePersonnel

longData['OffensePersonnel'].replace(to_replace = {'1 RB, 1 TE, 3 WR' : '1 QB, 5 OL, 1 RB, 1 TE, 3 WR', 
                                                   '1 RB, 2 TE, 2 WR' : '1 QB, 5 OL, 1 RB, 2 TE, 2 WR',  
                                                   '2 RB, 1 TE, 2 WR' : '1 QB, 5 OL, 2 RB, 1 TE, 2 WR',  
                                                   '1 RB, 3 TE, 1 WR' : '1 QB, 5 OL, 1 RB, 3 TE, 1 WR',  
                                                   '2 RB, 2 TE, 1 WR' : '1 QB, 5 OL, 2 RB, 2 TE, 1 WR', 
                                                   '2 RB, 0 TE, 3 WR' : '1 QB, 5 OL, 2 RB, 0 TE, 3 WR',  
                                                   '1 RB, 0 TE, 4 WR' : '1 QB, 5 OL, 1 RB, 0 TE, 4 WR', 
                                                   '2 RB, 3 TE, 0 WR' : '1 QB, 5 OL, 2 RB, 3 TE, 0 WR', 
                                                   '3 RB, 1 TE, 1 WR' : '1 QB, 5 OL, 3 RB, 1 TE, 1 WR',  
                                                   '3 RB, 0 TE, 2 WR' : '1 QB, 5 OL, 3 RB, 0 TE, 2 WR',  
                                                   '0 RB, 2 TE, 3 WR' : '1 QB, 5 OL, 0 RB, 2 TE, 3 WR',  
                                                   '1 RB, 4 TE, 0 WR' : '1 QB, 5 OL, 1 RB, 4 TE, 0 WR',  
                                                   '3 RB, 2 TE, 0 WR' : '1 QB, 5 OL, 3 RB, 2 TE, 0 WR',  
                                                   '0 RB, 3 TE, 2 WR' : '1 QB, 5 OL, 0 RB, 3 TE, 2 WR',  
                                                   '0 RB, 0 TE, 5 WR' : '1 QB, 5 OL, 0 RB, 0 TE, 5 WR',
                                                   '0 RB, 1 TE, 4 WR' : '1 QB, 5 OL, 0 RB, 1 TE, 4 WR'
                                                  }, inplace = True)

longData['OffensePersonnel'].replace(to_replace = {'6 OL, 3 RB, 0 TE, 1 WR' : '1 QB, 6 OL, 3 RB, 0 TE, 1 WR', 
                                                   '6 OL, 0 RB, 2 TE, 2 WR' : '1 QB, 6 OL, 0 RB, 2 TE, 2 WR', 
                                                   '6 OL, 2 RB, 0 TE, 2 WR' : '1 QB, 6 OL, 2 RB, 0 TE, 2 WR', 
                                                   '6 OL, 1 RB, 3 TE, 0 WR' : '1 QB, 6 OL, 1 RB, 3 TE, 0 WR', 
                                                   '6 OL, 1 RB, 0 TE, 3 WR' : '1 QB, 6 OL, 1 RB, 0 TE, 3 WR',
                                                   '6 OL, 2 RB, 2 TE, 0 WR' : '1 QB, 6 OL, 1 RB, 0 TE, 3 WR', 
                                                   '6 OL, 2 RB, 1 TE, 1 WR' : '1 QB, 6 OL, 2 RB, 1 TE, 1 WR', 
                                                   '6 OL, 1 RB, 1 TE, 2 WR' : '1 QB, 6 OL, 1 RB, 1 TE, 2 WR', 
                                                   '6 OL, 1 RB, 2 TE, 1 WR' : '1 QB, 6 OL, 1 RB, 2 TE, 1 WR'
                                                  }, inplace= True)

longData['OffensePersonnel'].replace(to_replace = {'7 OL, 1 RB, 0 TE, 2 WR' : '1 QB, 6 OL, 2 RB, 0 TE, 2 WR', 
                                                   '7 OL, 1 RB, 2 TE, 0 WR' : '1 QB, 6 OL, 2 RB, 2 TE, 0 WR', 
                                                   '7 OL, 1 RB, 1 TE, 1 WR' : '1 QB, 6 OL, 1 RB, 2 TE, 1 WR', 
                                                   '7 OL, 2 RB, 1 TE, 0 WR' : '1 QB, 6 OL, 3 RB, 1 TE, 0 WR',
                                                   '7 OL, 2 RB, 0 TE, 1 WR' : '1 QB, 6 OL, 3 RB, 0 TE, 1 WR',
                                                   '7 OL, 1 RB, 2 TE, 0 WR' : '1 QB, 6 OL, 2 RB, 2 TE, 0 WR'
                                                  }, inplace= True)

longData['OffensePersonnel'].replace(to_replace = {'1 RB, 1 TE, 2 WR,1 LB' : '1 QB, 5 OL, 2 RB, 1 TE, 2 WR', 
                                                   '1 RB, 0 TE, 3 WR,1 DB' : '1 QB, 5 OL, 1 RB, 0 TE, 4 WR', 
                                                   '2 QB, 2 RB, 0 TE, 2 WR' : '1 QB, 5 OL, 3 RB, 0 TE, 2 WR', 
                                                   '1 RB, 2 TE, 1 WR,1 DB' : '1 QB, 5 OL, 1 RB, 2 TE, 2 WR', 
                                                   '2 QB, 1 RB, 3 TE, 0 WR' : '1 QB, 5 OL, 2 RB, 3 TE, 0 WR', 
                                                   '6 OL, 1 RB, 0 TE, 2 WR,1 LB' : '1 QB, 6 OL, 2 RB, 0 TE, 2 WR', 
                                                   '2 RB, 2 TE, 0 WR,1 DL' : '1 QB, 6 OL, 2 RB, 2 TE, 0 WR', 
                                                   '7 OL, 1 RB, 1 TE, 0 WR,1 LB' : '1 QB, 6 OL, 3 RB, 1 TE, 0 WR', 
                                                   '2 QB, 2 RB, 2 TE, 0 WR' : '1 QB, 5 OL, 3 RB, 2 TE, 0 WR', 
                                                   '2 RB, 3 TE, 1 WR' : '1 QB, 5 OL, 1 RB, 3 TE, 1 WR', 
                                                   '1 RB, 3 TE, 0 WR,1 DB' : '1 QB, 5 OL, 1 RB, 3 TE, 1 WR', 
                                                   '6 OL, 1 RB, 1 TE, 1 WR,1 LB' : '1 QB, 6 OL, 2 RB, 1 TE, 1 WR', 
                                                   '1 RB, 2 TE, 3 WR' : '1 QB, 5 OL, 1 RB, 2 TE, 2 WR', 
                                                   '2 RB, 1 TE, 1 WR,1 DB' : '1 QB, 5 OL, 2 RB, 1 TE, 2 WR', 
                                                   '6 OL, 1 RB, 1 TE, 0 WR,2 DL' : '1 QB, 6 OL, 3 RB, 1 TE, 0 WR', 
                                                   '2 QB, 3 RB, 1 TE, 0 WR' : '1 QB, 6 OL, 3 RB, 1 TE, 0 WR', 
                                                  }, inplace=True)

longData['OffensePersonnel'].replace(to_replace = {'1 RB, 2 TE, 1 WR,1 DL' : '1 QB, 6 OL, 1 RB, 2 TE, 1 WR', 
                                                   '2 QB, 1 RB, 1 TE, 2 WR' : '1 QB, 5 OL, 2 RB, 1 TE, 2 WR',
                                                   '1 RB, 1 TE, 2 WR,1 DL' : '1 QB, 6 OL, 1 RB, 1 TE, 2 WR', 
                                                   '2 QB, 2 RB, 1 TE, 1 WR' : '1 QB, 5 OL, 3 RB, 1 TE, 1 WR', 
                                                   '1 RB, 3 TE, 0 WR,1 DL' : '1 QB, 6 OL, 1 RB, 3 TE, 0 WR',
                                                   '2 QB, 1 RB, 2 TE, 1 WR' : '1 QB, 5 OL, 2 RB, 2 TE, 1 WR', 
                                                   '6 OL, 1 RB, 2 TE, 0 WR,1 LB' : '1 QB, 6 OL, 2 RB, 2 TE, 0 WR', 
                                                   '6 OL, 1 RB, 2 TE, 0 WR,1 DL' : '1 QB, 6 OL, 2 RB, 2 TE, 0 WR', 
                                                   '1 RB, 2 TE, 1 WR,1 LB' : '1 QB, 5 OL, 2 RB, 2 TE, 1 WR', 
                                                   '1 RB, 1 TE, 2 WR,1 DB' : '1 QB, 5 OL, 1 RB, 1 TE, 3 WR', 
                                                   '6 OL, 2 RB, 1 TE, 0 WR,1 DL' : '1 QB, 6 OL, 3 RB, 1 TE, 0 WR', 
                                                   '2 QB, 1 RB, 0 TE, 3 WR' : '1 QB, 5 OL, 2 RB, 0 TE, 3 WR', 
                                                   '2 QB, 6 OL, 1 RB, 1 TE, 1 WR' : '1 QB, 6 OL, 2 RB, 1 TE, 1 WR', 
                                                   '6 OL, 1 RB, 1 TE, 1 WR,1 DL' : '1 QB, 6 OL, 2 RB, 1 TE, 1 WR',
                                                   '1 RB, 3 TE, 0 WR,1 LB' : '1 QB, 5 OL, 2 RB, 3 TE, 0 WR'
                                                  }, inplace= True)

In [8]:
def labelRB(OffensePersonnel):
    groups = OffensePersonnel.split(',')
    for group in groups:
        if "RB" in group:
            backs = [int(x) for x in group if x.isdigit()]
            backs = backs[0]
            return backs

longData['RB'] = longData['OffensePersonnel'].apply(labelRB)

In [9]:
def labelTE(OffensePersonnel):
    groups = OffensePersonnel.split(',')
    for group in groups:
        if "TE" in group:
            ends = [int(x) for x in group if x.isdigit()]
            ends = ends[0]
            return ends
        
longData['TE'] = longData['OffensePersonnel'].apply(labelTE)

In [10]:
def labelWR(OffensePersonnel):
    groups = OffensePersonnel.split(',')
    for group in groups:
        if "WR" in group:
            receivers = [int(x) for x in group if x.isdigit()]
            receivers = receivers[0]
            return receivers

longData['WR'] = longData['OffensePersonnel'].apply(labelWR)

In [11]:
def labelOL(OffensePersonnel):
    groups = OffensePersonnel.split(',')
    for group in groups:
        if "OL" in group:
            linemen = [int(x) for x in group if x.isdigit()]
            linemen = linemen[0]
            return linemen

longData['OL'] = longData['OffensePersonnel'].apply(labelOL)

In [12]:
longData.drop(columns=['OffensePersonnel'], axis=1, inplace=True)

In [13]:
# The below code fixes incorrect names and is included in the data
# cleaning module:

longData['PossessionTeam'].replace(to_replace= {'ARZ':'ARI', 'BLT':'BAL',
                                                  'CLV':'CLE', 'HST':'HOU'}, 
                                    inplace= True)

longData['FieldPosition'].replace(to_replace= {'ARZ':'ARI', 'BLT':'BAL',
                                                  'CLV':'CLE', 'HST':'HOU'}, 
                                    inplace= True)

In [14]:
longData.rename(columns={'PossessionTeam':'Team'}, inplace=True)

In [15]:
longData['isHome'] = 0

longData.loc[longData['Team'] == longData['HomeTeamAbbr'], 'isHome'] = 1 
longData.loc[longData['Team'] == longData['VisitorTeamAbbr'], 'isHome'] = 0

In [16]:
# establish categorical Opponent column

longData.loc[longData['Team'] == longData['HomeTeamAbbr'], 'Opponent'] = longData['VisitorTeamAbbr']
longData.loc[longData['Team'] == longData['VisitorTeamAbbr'], 'Opponent'] = longData['HomeTeamAbbr']

In [17]:
longData['ScoreBeforePlay'] = 0
longData['OppScoreBeforePlay'] = 0

In [18]:
longData.loc[longData['isHome'] == 1, 'ScoreBeforePlay'] = longData['HomeScoreBeforePlay']
longData.loc[longData['isHome'] == 0, 'ScoreBeforePlay'] = longData['VisitorScoreBeforePlay']

longData.loc[longData['isHome'] == 1, 'OppScoreBeforePlay'] = longData['VisitorScoreBeforePlay']
longData.loc[longData['isHome'] == 0, 'OppScoreBeforePlay'] = longData['HomeScoreBeforePlay']

# after running this, rerun team_columns cell above to check work

In [19]:
longData.drop(columns=['HomeScoreBeforePlay', 'VisitorScoreBeforePlay', 'HomeTeamAbbr', 'VisitorTeamAbbr'], axis=1, inplace=True)

In [20]:
longData.rename(columns={'Distance':'YardsToFirst'}, inplace=True)

In [21]:
longData['YardsToTD'] = 0
longData['YardsToFGRange'] = 0

longData.loc[longData['FieldPosition'] == np.NaN, 'YardsToTD'] = 50
longData.loc[longData['FieldPosition'] == np.NaN, 'YardsToFGRange'] = 15

# if team = fieldposition, then

In [ ]:
longData['DefensePersonnel'].value_counts()

In [23]:
team_columns = pd.DataFrame()
team_columns['Team'] = longData['Team']
team_columns['isHome'] = longData['isHome']
team_columns['Opponent'] = longData['Opponent']
team_columns['ScoreBeforePlay'] = longData['ScoreBeforePlay']
team_columns['OppScoreBeforePlay'] = longData['OppScoreBeforePlay']

team_columns.head(45)

      Team  isHome Opponent  ScoreBeforePlay  OppScoreBeforePlay
35303  CHI       1      PIT                0                   0
35325  CHI       1      PIT                0                   0
35347  CHI       1      PIT                0                   0
35369  CHI       1      PIT                0                   0
35391  CHI       1      PIT                0                   0
35414  CHI       1      PIT                0                   0
35480  CHI       1      PIT                7                   0
35501  CHI       1      PIT                7                   0
35524  CHI       1      PIT                7                   0
35546  CHI       1      PIT                7                   0
35569  CHI       1      PIT                7                   0
35590  CHI       1      PIT                7                   0
35701  CHI       1      PIT                7                   7
35723  CHI       1      PIT                7                   7
35744  CHI       1      PIT                7                   7
35766  CHI       1      PIT                7                   7
35788  CHI       1      PIT                7                   7
35810  CHI       1      PIT               17                   7
35855  CHI       1      PIT               17                   7
35876  CHI       1      PIT               17                   7
35943  CHI       1      PIT               17                  14
35964  CHI       1      PIT               17                  14
35987  CHI       1      PIT               17                  14
36009  CHI       1      PIT               17                  14
36029  CHI       1      PIT               17                  14
36054  CHI       1      PIT               17                  14
36141  CHI       1      PIT               17                  14
36163  CHI       1      PIT               17                  14
36206  CHI       1      PIT               17                  17
36249  CHI       1      PIT               17                  17
36272  CHI       1      PIT               17                  17
36294  CHI       1      PIT               17                  17
36316  CHI       1      PIT               17                  17
36339  CHI       1      PIT               17                  17
36360  CHI       1      PIT               17                  17
46975  CHI       0       GB                0                  14
46997  CHI       0       GB                0                  14
47019  CHI       0       GB                0                  14
47063  CHI       0       GB                0                  14
47107  CHI       0       GB                0                  14
47129  CHI       0       GB                0                  14
47151  CHI       0       GB                0                  14
47173  CHI       0       GB                0                  14
47195  CHI       0       GB                0                  14
47305  CHI       0       GB                0                  14

In [ ]:
# successful play criteria: TD, 1rst down conversion,

In [22]:
longData

,GameId,PlayId,X,Y,S,A,Dis,Orientation,Dir,Season,YardLine,Quarter,GameClock,Team,Down,YardsToFirst,FieldPosition,NflIdRusher,OffenseFormation,DefendersInTheBox,DefensePersonnel,PlayDirection,TimeHandoff,TimeSnap,Yards,Week,Stadium,StadiumType,Turf,GameWeather,Temperature,Humidity,RB,TE,WR,OL,isHome,Opponent,ScoreBeforePlay,OppScoreBeforePlay,YardsToTD,YardsToFGRange
35303,2017092403,20170924030143,85.31,29.77,2.95,1.09,0.32,238.45,8.93,2017,26,1,832,CHI,1,10,CHI,2555418,SINGLEBACK,8.0,"3 DL, 4 LB, 4 DB",left,2017-09-24T17:06:41.000Z,2017-09-24T17:06:39.000Z,-1,3,Soldier Field,Outdoor,Grass,"Sunny, highs to upper 80s",89.0,48.0,1,3,1,5,1,PIT,0,0,0,0
35325,2017092403,20170924030239,37.76,33.83,5.25,1.34,0.51,188.65,336.10,2017,29,1,753,CHI,1,10,PIT,2558250,SINGLEBACK,7.0,"3 DL, 4 LB, 4 DB",left,2017-09-24T17:09:26.000Z,2017-09-24T17:09:24.000Z,4,3,Soldier Field,Outdoor,Grass,"Sunny, highs to upper 80s",89.0,48.0,1,2,2,5,1,PIT,0,0,0,0
35347,2017092403,20170924030260,35.62,26.16,4.59,0.91,0.49,121.29,188.30,2017,25,1,716,CHI,2,6,PIT,2555418,I_FORM,7.0,"3 DL, 4 LB, 4 DB",left,2017-09-24T17:10:03.000Z,2017-09-24T17:10:01.000Z,11,3,Soldier Field,Outdoor,Grass,"Sunny, highs to upper 80s",89.0,48.0,2,1,2,5,1,PIT,0,0,0,0
35369,2017092403,20170924030302,21.98,30.70,0.44,2.46,0.10,152.84,113.02,2017,12,1,635,CHI,2,8,PIT,2555418,I_FORM,7.0,"3 DL, 4 LB, 4 DB",left,2017-09-24T17:11:31.000Z,2017-09-24T17:11:29.000Z,8,3,Soldier Field,Outdoor,Grass,"Sunny, highs to upper 80s",89.0,48.0,2,1,2,5,1,PIT,0,0,0,0
35391,2017092403,20170924030323,13.50,26.32,4.24,1.18,0.53,105.38,209.43,2017,4,1,590,CHI,1,4,PIT,2555418,SINGLEBACK,8.0,"3 DL, 4 LB, 4 DB",left,2017-09-24T17:12:15.000Z,2017-09-24T17:12:14.000Z,1,3,Soldier Field,Outdoor,Grass,"Sunny, highs to upper 80s",89.0,48.0,1,3,1,5,1,PIT,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498809,2018123005,20181230050681,93.59,29.18,2.63,2.19,0.26,257.21,338.18,2018,15,1,254,CHI,2,7,CHI,2555418,SINGLEBACK,8.0,"4 DL, 3 LB, 4 DB",left,2018-12-30T21:54:54.000Z,2018-12-30T21:54:52.000Z,1,17,U.S. Bank Stadium,Indoors,Field Turf,N/A (Indoors),NaN,0.0,1,1,2,6,0,MIN,7,0,0,0
498851,2018123005,20181230051262,48.02,19.81,2.86,0.12,0.29,166.93,176.66,2018,39,2,582,CHI,1,10,CHI,2558250,SHOTGUN,6.0,"4 DL, 2 LB, 5 DB",right,2018-12-30T22:19:12.000Z,2018-12-30T22:19:10.000Z,6,17,U.S. Bank Stadium,Indoors,Field Turf,N/A (Indoors),NaN,0.0,1,1,3,5,0,MIN,7,0,0,0
498875,2018123005,20181230051284,54.56,21.52,1.40,1.57,0.13,262.81,262.12,2018,45,2,547,CHI,2,4,CHI,2555418,SINGLEBACK,7.0,"4 DL, 3 LB, 4 DB",right,2018-12-30T22:19:47.000Z,2018-12-30T22:19:46.000Z,11,17,U.S. Bank Stadium,Indoors,Field Turf,N/A (Indoors),NaN,0.0,1,1,2,6,0,MIN,7,0,0,0
498896,2018123005,20181230051308,66.27,23.47,2.23,0.49,0.22,119.41,38.81,2018,44,2,509,CHI,1,10,MIN,2555418,SHOTGUN,6.0,"4 DL, 2 LB, 5 DB",right,2018-12-30T22:20:25.000Z,2018-12-30T22:20:24.000Z,3,17,U.S. Bank Stadium,Indoors,Field Turf,N/A (Indoors),NaN,0.0,1,1,3,5,0,MIN,7,0,0,0
498918,2018123005,20181230051413,108.39,27.62,1.12,0.56,0.11,82.62,192.42,2018,1,2,440,CHI,1,1,MIN,2555418,SHOTGUN,8.0,"5 DL, 1 LB, 5 DB",right,2018-12-30T22:25:58.000Z,2018-12-30T22:25:57.000Z,1,17,U.S. Bank Stadium,Indoors,Field Turf,N/A (Indoors),NaN,0.0,1,1,3,5,0,MIN,7,0,0,0